kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: default-test
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
    storage: 10Gi
