apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: default-test
 annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
 labels:
  kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-disk
