apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-research
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-research
  template:
    metadata:
      labels:
        app: pod-research
    spec:
      containers:
      - name: pod-research
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
        image: panupongdeve/node-pods-research:v0.0.1
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 600m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi