kind: Endpoints
apiVersion: v1
metadata:
 name: external-ip-database
subsets:
  - addresses:
    - ip: 172.217.27.227
    - ip: 172.217.27.221
    ports:
    - port: 80
      name: http
    - port: 3000
      name: tcp