apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: my-volume
spec:
 accessModes:
 - ReadWriteMany
 capacity:
  storage: 1Gi
 nfs:
  server: 10.96.136.6
  path: "/exports"
